# Generated by Django 4.2.3 on 2023-07-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_image', models.ImageField(upload_to='')),
                ('company_name', models.CharField(max_length=100)),
                ('button_text', models.CharField(max_length=100)),
                ('b1_title', models.CharField(max_length=100)),
                ('b1_big_text', models.TextField()),
                ('b1_lit_text', models.TextField()),
                ('b2_title', models.CharField(max_length=100)),
                ('b2_big_text', models.TextField()),
                ('b2_lit_text', models.TextField()),
                ('card_image', models.ImageField(upload_to='')),
                ('year_land', models.CharField(max_length=200)),
                ('card_text', models.TextField()),
            ],
        ),
    ]
