# Generated by Django 4.2.3 on 2023-07-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='feedback_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
