# Generated by Django 4.2.3 on 2023-07-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_main_feedback_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='student_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
