# Generated by Django 4.2.3 on 2023-07-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_main_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_title', models.CharField(max_length=100, null=True)),
                ('student_name', models.CharField(max_length=100, null=True)),
                ('card_image', models.ImageField(upload_to='')),
                ('year_land', models.CharField(max_length=200)),
                ('card_text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='main',
            name='card_image',
        ),
        migrations.RemoveField(
            model_name='main',
            name='card_text',
        ),
        migrations.RemoveField(
            model_name='main',
            name='feedback_title',
        ),
        migrations.RemoveField(
            model_name='main',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='main',
            name='year_land',
        ),
    ]
