# Generated by Django 4.2.3 on 2023-08-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=50)),
                ('ferienjob', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('contacts', models.CharField(max_length=50)),
            ],
        ),
    ]
