# Generated by Django 4.2.3 on 2023-08-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_navbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=100)),
                ('title_form', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('mail', models.EmailField(max_length=256)),
                ('theme', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('name_placeholder', models.CharField(max_length=100)),
                ('email_placeholder', models.CharField(max_length=100)),
                ('theme_placeholder', models.CharField(max_length=100)),
                ('message_placeholder', models.CharField(max_length=100)),
                ('title_address', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_num', models.CharField(max_length=13)),
                ('mail_contacts', models.EmailField(max_length=250)),
                ('map_link', models.TextField()),
            ],
        ),
    ]
