# Generated by Django 4.2.3 on 2023-08-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_contact_form_remove_contacts_mail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_form',
            name='small_title',
        ),
        migrations.RemoveField(
            model_name='contact_form',
            name='title_form',
        ),
        migrations.AddField(
            model_name='contacts',
            name='small_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='title_form',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
