# Generated by Django 4.2.3 on 2023-08-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_remove_contact_form_small_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('first_name_pl', models.CharField(max_length=100)),
                ('last_name_pl', models.CharField(max_length=100)),
                ('phone_pl', models.CharField(max_length=100)),
                ('age_pl', models.CharField(max_length=100)),
                ('mail_pl', models.CharField(max_length=100)),
                ('education_pl', models.CharField(max_length=100)),
                ('category_title', models.CharField(max_length=100)),
                ('level_title', models.CharField(max_length=100)),
            ],
        ),
    ]
