# Generated by Django 4.2.3 on 2023-08-14 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_form_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='email_placeholder',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='message_placeholder',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='name_placeholder',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='theme_placeholder',
        ),
        migrations.RemoveField(
            model_name='form_page',
            name='age_pl',
        ),
        migrations.RemoveField(
            model_name='form_page',
            name='category_title',
        ),
        migrations.RemoveField(
            model_name='form_page',
            name='education_pl',
        ),
        migrations.RemoveField(
            model_name='form_page',
            name='first_name_pl',
        ),
        migrations.RemoveField(
            model_name='form_page',
            name='last_name_pl',
        ),
        migrations.RemoveField(
            model_name='form_page',
            name='level_title',
        ),
        migrations.RemoveField(
            model_name='form_page',
            name='mail_pl',
        ),
        migrations.RemoveField(
            model_name='form_page',
            name='phone_pl',
        ),
    ]
