# Generated by Django 4.2.3 on 2023-08-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_remove_contacts_email_placeholder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_page',
            name='background',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
