# Generated by Django 4.2.3 on 2023-08-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_form_page_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_page',
            name='age_label',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='form_page',
            name='category_label',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='form_page',
            name='course_choose',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='form_page',
            name='deLevel_label',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='form_page',
            name='ferienjob_choose',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='form_page',
            name='firstname_label',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='form_page',
            name='lastname_label',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='form_page',
            name='levelA1_choose',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='form_page',
            name='levelA2_choose',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='form_page',
            name='levelB1_choose',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='form_page',
            name='levelB2_choose',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='form_page',
            name='mail_label',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='form_page',
            name='phone_label',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
