# Generated by Django 4.2.3 on 2023-08-17 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_form_page_age_label_form_page_category_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_page',
            name='age_label',
        ),
        migrations.RemoveField(
            model_name='form_page',
            name='category_label',
        ),
        migrations.RemoveField(
            model_name='form_page',
            name='course_choose',
        ),
        migrations.RemoveField(
            model_name='form_page',
            name='deLevel_label',
        ),
        migrations.RemoveField(
            model_name='form_page',
            name='ferienjob_choose',
        ),
        migrations.RemoveField(
            model_name='form_page',
            name='firstname_label',
        ),
        migrations.RemoveField(
            model_name='form_page',
            name='lastname_label',
        ),
        migrations.RemoveField(
            model_name='form_page',
            name='levelA1_choose',
        ),
        migrations.RemoveField(
            model_name='form_page',
            name='levelA2_choose',
        ),
        migrations.RemoveField(
            model_name='form_page',
            name='levelB1_choose',
        ),
        migrations.RemoveField(
            model_name='form_page',
            name='levelB2_choose',
        ),
        migrations.RemoveField(
            model_name='form_page',
            name='mail_label',
        ),
        migrations.RemoveField(
            model_name='form_page',
            name='phone_label',
        ),
    ]
