# Generated by Django 4.2.3 on 2023-08-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_remove_form_page_age_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_registr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=13)),
                ('age', models.IntegerField()),
                ('mail', models.EmailField(max_length=256)),
            ],
        ),
    ]
