# Generated by Django 4.2.3 on 2023-08-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_form_registr'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_registr',
            name='category',
            field=models.CharField(choices=[('Языковые курсы', 'Языковые курсы'), ('Ferienjob', 'Ferienjob')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='form_registr',
            name='level',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2+', 'B2+')], max_length=60, null=True),
        ),
    ]
