# Generated by Django 4.2.3 on 2023-08-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_form_registr_category_form_registr_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='form_registr',
            name='category',
        ),
        migrations.AddField(
            model_name='form_registr',
            name='category',
            field=models.ManyToManyField(null=True, to='backend.categories'),
        ),
    ]
