# Generated by Django 4.2.3 on 2023-08-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_alter_form_registr_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form_registr',
            name='category',
        ),
        migrations.AddField(
            model_name='form_registr',
            name='course',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='form_registr',
            name='ferienjob',
            field=models.BooleanField(null=True),
        ),
    ]
