# Generated by Django 4.2.3 on 2023-08-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_remove_form_registr_category_form_registr_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_page',
            name='saved_text',
            field=models.TextField(null=True),
        ),
    ]
