# Generated by Django 4.2.3 on 2023-08-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_form_page_saved_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.AlterField(
            model_name='contact_form',
            name='theme',
            field=models.CharField(max_length=200),
        ),
    ]
