# Generated by Django 4.2.3 on 2023-08-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_delete_categories_alter_contact_form_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='button_form',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='form_page',
            name='button_text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
